// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcWZjWDtSgcT1WkBYTus9txF_O4avjnlg',
    appId: '1:7310437116:web:c53e30ec5f511bf75d0579',
    messagingSenderId: '7310437116',
    projectId: 'meta-dash-9a4f3',
    authDomain: 'meta-dash-9a4f3.firebaseapp.com',
    storageBucket: 'meta-dash-9a4f3.firebasestorage.app',
    measurementId: 'G-BG32XZG5C8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvDhXkPRjdC0m45sK6vSiEmfqMUKHbKZ4',
    appId: '1:7310437116:android:a5bd7418af1400045d0579',
    messagingSenderId: '7310437116',
    projectId: 'meta-dash-9a4f3',
    storageBucket: 'meta-dash-9a4f3.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfvDB9dQ1YX4YwpUfeGzCKa3sT1tYNEz0',
    appId: '1:7310437116:ios:6f5e607dba5d4fac5d0579',
    messagingSenderId: '7310437116',
    projectId: 'meta-dash-9a4f3',
    storageBucket: 'meta-dash-9a4f3.firebasestorage.app',
    androidClientId:
        '7310437116-b258t1fhqsjgnd0p803j3kc9d8g2haoj.apps.googleusercontent.com',
    iosClientId:
        '7310437116-vhlq8oh00mi8spomgdv7tbj33iv795sd.apps.googleusercontent.com',
    iosBundleId: 'app.Metadash',
  );
}
